@startuml

title SYDER Order Sequence diagram
footer Page %page% of %lastpage%

actor Sender
actor Receiver
control Laravel
database RDS
boundary FCM
boundary Car
control Node.js

==차량 요청 전==

Receiver -> Laravel : 로그인

activate Sender
    activate Laravel
        Sender -> Laravel : 로그인
        Sender -> Laravel : Request : ID, PW 입력, 웨이포인트/경로
        Laravel -> RDS : Query : ID, PW 확인

        alt 로그인 실패
            RDS --> Laravel : Query : 일치하는 ID, PW 가 없음
            Laravel --> Sender : Response : 로그인 에러

        else 로그인 성공
            RDS -> RDS : 액세스 토큰 발급
            RDS --> Laravel : Query : 유저정보, 액세스 토큰, 웨이포인트/경로
            Laravel -> FCM : Request : FCM 토큰
            FCM --> Laravel : Response : FCM 토큰
            Laravel --> Sender : Response : 유저정보, 액세스/FCM 토큰, 웨이포인트/경로
        end
    deactivate Laravel

    Sender -> Laravel : Response : 등록된 요청 정보 조회(토큰)

    activate Laravel
        Laravel -> RDS : Query : 요청 목록 조회

        alt 진행 중인 요청 존재
            RDS -> Laravel : Query : 요청 정보 조회 결과
            Laravel --> Sender : Response : 요청 정보 조회 결과
    deactivate Laravel
        end

    note right
        등록된 요청이 존재할 경우,
        추가 요청 불가
    end note
deactivate Sender

==차량 요청==

Sender -> Sender : 출발~도착지 입력, 예상 소요시간 확인
activate Sender
Sender -> Laravel : Request : 요청 가능 여부 조회

activate Laravel
    Laravel -> RDS : Request : 가용 차량 조회
    RDS --> Laravel : Response : 가용 차량 조회 결과
        alt 가용 차량이 없을 경우
            Laravel -> RDS : Query : 대기 요청 건수 조회
            RDS --> Laravel : Query : 대기 요청 건수
            Laravel --> Sender : Response : 대기 요청 건수
        end

        alt  가용 차량이 있지만, 출발지에 없을 경우
            Laravel -> RDS : Query : 출발지에 차량 도착 예상시간 조회
            RDS --> Laravel : Query : 출발지에 차량 도착 예상시간
            Laravel --> Sender : Response : 차량 출발지 도착 예상 시간
        end
    deactivate Laravel
deactivate Sender

    RDS -> RDS : 차량 상태 운행 예약 변경
        note left
            운행 예약 상태에서 일정시간
            (운행 요청 미실시)초과 시, 운행 취소
        end note

    Sender -> Laravel : Request : 수신자 연락처 입력, 정보 요청
activate Sender
    activate Laravel
        Laravel -> RDS : Query : 수신자 정보 조회

        alt 등록된 수신자가 없을 경우
            RDS --> Laravel : Query : 등록된 수신자 없음
            Laravel --> Sender : Response : 수신자 정보 조회 거절
        else 등록된 수신자가 있을 경우
            RDS --> Laravel : Response : 수신자 정보
            Laravel -> FCM : Query : 수신자 FCM 토큰 조회
            FCM --> Laravel : Query : 수신자 FCM 토큰
            Laravel --> Sender : Response : 수신자 정보 자동입력, FCM 토큰(요청 간 유지)
        end
    deactivate Laravel
deactivate Sender

Sender -> Laravel : Request : 차량 호출 요청(수신자 FCM 토큰)
activate Sender
    activate Laravel
        Laravel -> RDS : Query : 요청 정보 등록
        Laravel -> Receiver : Alert : 수신자 동의 요청


        alt 동의 요청 거절 시
            activate Receiver
                Receiver --> Laravel : Reaction : 수신자 거절 메세지
                Laravel --> Sender : Response : 수신자 거절 메세지 전달
                Laravel -> RDS : Query : 요청 정보 취소
        else 요청 동의 시
            Receiver --> Laravel : Reaction : 수신자 동의 메세지
            deactivate Receiver

        Laravel --> Sender : Response : 수신자 동의 메세지 전달
        Laravel -> RDS : Query : 요청 상태 최신화
    deactivate Laravel
end

Sender -> Node.js : Request : 요청 시작 요청

    activate Node.js
        alt 가용 차량이 있지만, 출발지에 없을 경우
            Node.js -> Car : Request : 출발지로 차량 출발 명령 전송
            Car -> Car : 출발지로 차량 이동
            Car --> Node.js : Response : 출발지에 차량 도착 완료
        end

        Node.js --> FCM : 출발지 차량 도착 전송
    deactivate Node.js
    FCM -> Sender : Response : 출발지 차량 도착 완료

deactivate Sender

newpage

==차량 출발==

Sender <--> Car : QR코드 확인
activate Sender
Sender -> Laravel : Request : QR코드 인증을 통한 요청 정보 확인 요청
activate Laravel
Laravel -> RDS : Query : 요청 정보 조회
alt 등록된 요청 정보 없을 경우
RDS --> Laravel : Query : 등록된 요청 정보 없음
Laravel --> Sender : Response : 정보 확인 거절
else 등록된 요청 정보 있을 경우
RDS --> Laravel : Query : 요청 정보
Laravel --> Sender : Response : 요청 정보 전송
deactivate Laravel

Sender -> Node.js : Request : 차량 개방 요청
activate Node.js
Node.js --> Car : Alert : 차량 개방 요청 전송
activate Car
Car -> Car : 차량 개방
activate Car
Sender <--> Car : 차량에 물건 적재
deactivate Car
Sender -> Node.js : Request : 차량 출발 요청ㄱㄷ
deactivate Sender

Node.js --> Car : Alert : 차량 출발 명령 전송
Car -> Node.js : Reaction : 차량 출발
deactivate Car

Node.js --> Receiver : Alert : 차량 출발 전달
deactivate Node.js
end
==차량 이동==
Car -> Node.js : Response 실시간 이동 좌표
Node.js -> Receiver   : Response : 실시간 이동 좌표
Node.js -> Sender : Response : 실시간 이동 좌표

==차량 도착, 요청 완료==
alt Car arrive for Receiver

Car --> Node.js : Response : 차량 도착
activate Node.js
Node.js -> FCM : 차량 도착 전달
FCM --> Receiver: 차량 도착 전달


Receiver <--> Car : QR코드 확인
activate Receiver
Receiver -> Laravel:Request : Request :QR코드 인증을 통한 요청 정보 확인 요청
activate Laravel
Laravel-> RDS : Query 요청 정보 조회
alt 등록된 요청 정보 없을 경우
RDS --> Laravel : Query 등록된 정보 없음
Laravel -> Receiver : 정보 확인 거절
end
RDS --> Laravel : Query 요청 정보
Laravel -> Receiver : Response 요청 정보 전송
deactivate Laravel

Receiver -> Node.js : Request : 차량 개방 요청
deactivate Receiver

Node.js -> Car : Alert : 차량 개방 요청 전송
activate Car
Car -->Car: 차량 개방
activate Car
Receiver --> Car : 차량에 적재된 물건 수령
deactivate Car
Receiver -> Node.js : Request : 수령 완료
Node.js --> FCM : 수령 완료 전달
FCM --> Receiver : Alert : 수령 완료
Node.js --> FCM : 수령 완료 전달
FCM --> Sender : Alert : 수령 완료
Node.js -> RDS : 요청 종료
deactivate Node.js
deactivate Car
end

@endduml
